version: "3"

services:
  api:
    build: ./
    image: 09035077346/user_api:1.0.1-$GITHUB_RUN_ID
    command: uvicorn user_api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - api_network

networks: 
  api_network:
    driver: bridge
