name: Build API

on: [ push ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        #run: |
        #  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker-compose build
        run: |
          docker-compose build
      - name: docker push
        run: |
          docker-compose push

